### ISSUE TITLE
Hello, I need some help with a few issues.

### ISSUE THREAD

**Issue by willOcean1** [issp-center-dev/HPhi#172]
1. I encountered an error while running my code. Is it because the number of iterations is too low (default is 2000)? However, blindly increasing the number of iterations will raise the computational cost. How should I make a trade-off?
![image](https://github.com/user-attachments/assets/6604af37-e896-4dde-9e0c-c09fb209f93c)

2. I want to calculate fidelity and entanglement entropy. How should I do it?

**Comment by ultimatile** [comment]
1. Please provide your input file(s) so that we can reproduce your issue. With the current information, we cannot assist you.
2. Calculations of fidelity and entanglement entropy are currently not supported. You will need to implement your own code to calculate them using the eigenstate vectors output by HPhi. Please include `EigenvecIO = "out"` in your input file if you are using standard mode to output the eigenstates. If you are using expert mode, change the value to the right of `OutputEigenVec` in `calcmod.def` from `0` to `1`. The data format for the output eigenstates is described in [the manual](https://issp-center-dev.github.io/HPhi/manual/master/en/html/filespecification/outputfiles_en/eigenvec_en.html).

**Comment by yomichi** [comment]
FYI, there is an example for calculating the inner product of eigenstates in HPhi tutorial (https://issp-center-dev.github.io/HPhi/manual/develop/tutorial/en/html/zero_temperature/vector.html).
A python script for loading eigenvectors is available in this tutorial.
