### ISSUE TITLE
The results of different kernel numbers are different.

### ISSUE THREAD

**Issue by sidy1073662254** [issp-center-dev/HPhi#175]
I recently run the program at .../samples/tutorial_2.1/stan3.in. However, the results is different when I loaded 20 kernels and 40 kernels.

When I loaded 20 kernels, 
![截图20240731002909](https://github.com/user-attachments/assets/fd758eeb-a8c3-4aba-80c4-1a6c0a0f411e)

When I loaded 40 kernels, 
![截图20240731002749](https://github.com/user-attachments/assets/6ed0e1b4-99cd-4f08-a287-ccd988807b0e)

Which result is right? And how to unify the results of different kernel numbers?

**Comment by k-yoshimi** [comment]
Since mTPQ depends on the initial state, it must be averaged over several initial states given different random number seeds. Please refer to the following URL: 
https://issp-center-dev.github.io/HPhi/manual/develop/tutorial/en/html/finite_temperature/spin_chain.html#mtpq-method-susceptibility

>  how to unify the results of different kernel numbers?

If the same initial state is prepared, the results are expected to be consistent, even if the kernels are different (although small differences in numerical errors due to parallel processing, such as OpenMP and MPI, may cause deviations in sensitive cases where the results are affected).
