### ISSUE TITLE
Hello, I encountered an issue while using HPhi. Could you help me resolve it?

### ISSUE THREAD

**Issue by willOcean1** [issp-center-dev/HPhi#187]
Hello, I encountered some issues while calculating <Sz>. In the zvo_energy.dat file, <Sz> is given as a negative value, but when I calculate <Sz> using the zvo_cisajs_eigen0.dat file, I get a positive value (both are equal except for the sign). What could be the reason for this?
[stan.txt](https://github.com/user-attachments/files/17794340/stan.txt)
![image](https://github.com/user-attachments/assets/c67e7b50-a2c2-436f-9605-39896db79541)
[zvo_cisajs_eigen0.txt](https://github.com/user-attachments/files/17794344/zvo_cisajs_eigen0.txt)
This is the result I obtained through calculations using zvo_cisajs_eigen0.dat
![image](https://github.com/user-attachments/assets/bdb053bc-b42e-4628-a7d5-e79b396f0f26)

**Comment by ultimatile** [comment]
Briefly, the sign of `Sz` in `zvo_energy.dat` might be reversed.
`Sz` and cisajs are calculated differently, so they may differ due to different codes.

---

Below is the detail of the implementation.

At first glance, I'm unsure where the inverse sign comes from, so I only point out where it might be relevant.

The `Sz` in `zvo_energy.dat` should be calculated in:

https://github.com/issp-center-dev/HPhi/blob/366ebe7627ec8307eca9d0f3e7aa77b893ce41e1/src/expec_energy_flct.c#L578-L601

**Comment by tmisawa** [comment]
I noticed that  `Sz` in `zvo_energy.dat` is calculated by counting bit `1`
in the real space configuration.  Note that `pop` is the function of calculating bit `1`.
Since bit `1` corresponds to the down spin (`0` corresponds to the up spin), 
the sign of the `Sz` in `zvo_energy.dat` is incorrect.
So, `Sz` calculated from `zvo_cisajs` is the correct one.

I will correct the sign of `Sz` in `zvo_energy.dat` in a future release.

**Comment by willOcean1** [comment]
Hello, I have another question. When using expert mode to calculate the magnetic field along the [1 1 1] direction, should the sign in front of “-\sum t_{ij}...”be considered? I noticed someone asked this question before, and it seems that your answer took this negative sign into account.
![image](https://github.com/user-attachments/assets/58c8222c-0ae0-4dac-ac4a-91c92965cf76)
![image](https://github.com/user-attachments/assets/24655ffa-eafb-4e8a-ad4d-7bec825fe4ee)
![image](https://github.com/user-attachments/assets/e2e28aa3-0c4d-416a-aea4-3be4d0939810)


The first image shows the previous question, the second image shows your provided result (which seems to have considered the negative sign), and the third image shows my result, where the negative sign was not considered.

**Comment by tmisawa** [comment]
I think that the third image describes `-h* (Sx+Sy+Sz)` with `h=1`.
