### ISSUE TITLE
dstev for Lanczos

### ISSUE THREAD

**Issue by TMueller83** [issp-center-dev/HPhi#27]
Dear HPhi developers,

in the manual I read, that HPhi uses the LAPACK routine `dsyev` for the diagonalization of the tridiagonal matrix in the Lanczos mode. I wonder if the routine `dstev` which is designed especially for tridiagonal matrices could eventually speed up the process a little bit?

Kind regards.

**Comment by mitsuaki1987** [comment]
Dear TMueller83

There is no reason to use dsyev for the subspace diagonalization in the Lanczos method (Probably, the programer did not know dstev).
Although dstev is faster than dsyev, the acceleration is limited because this calculation is not the bottleneck of HPhi.

Best regards,
Mitsuaki Kawamura
