### ISSUE TITLE
Degenerate Ground state

### ISSUE THREAD

**Issue by rp092** [issp-center-dev/HPhi#47]
The hamiltonian

H = V Σ_ j n_ j n_ j+1 - t Σ_ j c*_j c_ j+1 + c*_ j+1 c_ j 

of a 1D chain with L=8 and N (number of fermions) = 4 and V>2t has a doubly degenerate ground state. Each one differs from the other in the phase of the charge-density wave. What ground state will HPhi calculate in that case?

thanks 
R.

**Comment by tmisawa** [comment]
@rp092 
In quantum systems, you can obtain the superposition
of the doubly degenerate classical charge ordered states
(In this superposition, translational symmetry is not broke).

Actually you can confirm this by performing the 
full diagonalization using HPhi (sample input files is shown below). 
================================
model = "Hubbard"
method = "fulldiag"
lattice = "chain"
L = 6
V = 4.0
t = 1.0
2Sz = 3
nelec = 3
================================

For L=8 or more generally even sites,
you can obtain doubly degenerate 
ground states due to the accidental degeneracy 
in the total momentum (K=0,pi).
In the double degenerate states obtained by HPhi,
the translational symmetry is apparently broken
because the states with different total momentum mix each other.

You can obtain the charge uniform state
by properly specifying the total momentum.
Unfortunately, we do not implement such function in HPhi.
Thus, if you want to specify the total momentum, 
it is necessary to change the codes properly.
