### ISSUE TITLE
unit cell

### ISSUE THREAD

**Issue by rp092** [issp-center-dev/HPhi#60]
Hi everyone,

I'm running HPhi to study a Fermion Hubbard chain lattice model with staggered potential. If only L is specified in the input file then does the unitary cell correspond to a single site of the chain in HPhi?

thanks a lot
R.

**Comment by tmisawa** [comment]
@rp092 
yes. If only L is specified, the unit cell includes only one site.
If you want to introduce staggered potential, please modify trans.def manually.

**Comment by rp092** [comment]
@tmisawa thanks for your reply.

To decide the size of the unit cell in a chain lattice do I have to specify only a1L in the input file?

To be more precise: given that I specified only L then the unit cell includes only one site as you told me. Let's overlook the particular hamiltonian of the system, I would like to study particle hole-excitations that break the symmetry of the unit cell of my system. In particular, starting with a unit cell with only one site after that excitation the unit cell will include 4 sites so q_exc = π/2. So my goal would be to specify from the beginning a unit cell that includes four sites in order to observe that excitation at q_exc =0. 

Hope I've been clear.
R.

**Comment by tmisawa** [comment]
@rp092 

Information of the unit cell is only necessary for performing
the Fourier transformation for the correlation functions 
as the post process. I mean that information of the unit cell
is NOT necessary for performing the HPhi calculations.

So, the procedure for the calculation may be summarized as follows:

1. prepare the input files using standard model
(at this stage unit cell includes only one site)

2. add staggered potentials in trans.def
(here unit cell may include two sites due to the 
staggered potential)

3. perform HPhi calculations and obtain the 
correlation functions.

4. perform the Fourier transformation for the obtained
correlation functions as the post process (it is necessary to
prepare a scripts for performing the Fourier transformation). 
Here, in performing the Fourier transformations, 
please note that the unit cell may include two sites.

**Comment by rp092** [comment]
So based on the hamiltonian of the system HPhi recognize automatically which is the right unit cell.
I didn't understand that.

Thanks a lot.

Riccardo

**Comment by tmisawa** [comment]
>So based on the hamiltonian of the system does HPhi recognize automatically which is the right unit cell? 

Unfortunately, HPhi does not automatically recognize the
information of the unit cell for the expert mode.
If you only use the standard mode,
fourier tool  utility automatically recognizes the
information of the unit cell.
However, once you manually modify the input files (e.g. trans.def),
fourier tool may not work correctly because the modifications may change
the size of the unit cell.
